
data:extend(
{
  {
    type = "fluid",
    name = "quadricyclane",
    default_temperature = 25,
    heat_capacity = "0.1KJ",
    base_color = {r=1, g=0, b=0},
    flow_color = {r=1, g=0, b=0},
    max_temperature = 100,
    icon = "__Darkstar_utilities__/graphics/icons/quadricyclane.png",
	icon_size = 32,
    pressure_to_speed_ratio = 0.4,
    flow_to_energy_ratio = 0.59,
    order = "a[fluid]-b[crude-oil]"
  },
  {
    type = "fluid",
    name = "norbornadiene",
    default_temperature = 25,
    heat_capacity = "0.1KJ",
    base_color = {r=1, g=1, b=0},
    flow_color = {r=1, g=1, b=0},
    max_temperature = 100,
    icon = "__Darkstar_utilities__/graphics/icons/norbornadiene.png",
	icon_size = 32,
    pressure_to_speed_ratio = 0.4,
    flow_to_energy_ratio = 0.59,
    order = "a[fluid]-b[crude-oil]"
  },
  {
    type = "fluid",
    name = "acetylene",
    default_temperature = 25,
    heat_capacity = "0.1KJ",
    base_color = {r=0.9, g=0.9, b=0.9},
    flow_color = {r=0.9, g=0.9, b=0.9},
    max_temperature = 100,
    icon = "__Darkstar_utilities__/graphics/icons/acetylene.png",
	icon_size = 32,
    pressure_to_speed_ratio = 0.4,
    flow_to_energy_ratio = 0.59,
    order = "a[fluid]-b[crude-oil]"
  },
  {
    type = "fluid",
    name = "cyclopentadiene",
    default_temperature = 25,
    heat_capacity = "0.1KJ",
    base_color = {r=0.9, g=0.9, b=0.7},
    flow_color = {r=0.9, g=0.9, b=0.7},
    max_temperature = 100,
    icon = "__Darkstar_utilities__/graphics/icons/cyclopentadiene.png",
	icon_size = 32,
    pressure_to_speed_ratio = 0.4,
    flow_to_energy_ratio = 0.59,
    order = "a[fluid]-b[crude-oil]"
  },
  {
    type = "fluid",
    name = "dark-matter",
    default_temperature = 25,
    heat_capacity = "0.1KJ",
    base_color = {r=0, g=0, b=0},
    flow_color = {r=0, g=0, b=0},
    max_temperature = 30,
    icon = "__Darkstar_utilities__/graphics/icons/cyclopentadiene.png",
	icon_size = 32,
    pressure_to_speed_ratio = 0.4,
    flow_to_energy_ratio = 0.59,
    order = "a[fluid]-b[crude-oil]"
  },
  {
    type = "fluid",
    name = "antithetical-matter",
    default_temperature = -5000,
    heat_capacity = "0.1KJ",
    base_color = {r=0, g=0, b=0.1},
    flow_color = {r=0, g=0, b=0.1},
    max_temperature = 5000,
    icon = "__Darkstar_utilities__/graphics/icons/antithetical-matter.png",
	icon_size = 32,
    pressure_to_speed_ratio = 0.4,
    flow_to_energy_ratio = 0.59,
    order = "a[fluid]-b[crude-oil]"
  },
  {
    type = "fluid",
    name = "quantum-waste",
    default_temperature = 31415,
    heat_capacity = "0.1KJ",
    base_color = {r=1, g=1, b=0},
    flow_color = {r=1, g=1, b=0},
    max_temperature = 31415,
    icon = "__Darkstar_utilities__/graphics/icons/quantum-waste.png",
	icon_size = 32,
    pressure_to_speed_ratio = 0.4,
    flow_to_energy_ratio = 0.59,
    order = "a[fluid]-b[crude-oil]"
  },
  {
    type = "fluid",
    name = "blood",
    default_temperature = 25,
    heat_capacity = "0.1KJ",
    base_color = {r=0.3, g=0, b=0},
    flow_color = {r=0.3, g=0, b=0},
    max_temperature = 100,
    icon = "__Darkstar_utilities__/graphics/icons/quadricyclane.png",
	icon_size = 32,
    pressure_to_speed_ratio = 0.4,
    flow_to_energy_ratio = 0.59,
    order = "a[fluid]-b[crude-oil]"
  },
})

